config/routes.rb
Rails.application.routes.draw do
  resources :route_points do
    collection do
      post 'multiple.json' => 'route_points#create_multiple'
     end
  end
  resources :trips
  root 'welcome#index'

end

app/models/route_point.rb
class RoutePoint < ActiveRecord::Base
  belongs_to :trip
end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/route_points_controller.rb
class RoutePointsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_route_point, only: [:show, :edit, :update, :destroy]

  # GET /route_points
  # GET /route_points.json
  def index
    @route_points = RoutePoint.all
  end

  # GET /route_points/1
  # GET /route_points/1.json
  def show
  end

  # GET /route_points/new
  def new
    @route_point = RoutePoint.new
  end

  # GET /route_points/1/edit
  def edit
  end

  # POST /route_points
  # POST /route_points.json
  def create
    respond_to do |format|
      format.html {
        @route_point = RoutePoint.new(route_point_params)
        if @route_point.save
          redirect_to @route_point, notice: 'Route point was successfully created.'
        else
          render :new
        end
      }
      format.json {
        route_point_params[:gps_time] = DateTime.parse(route_point_params[:gps_time])
        @route_point = RoutePoint.new(route_point_params)
        if @route_point.save
          render :show, status: :created, location: @route_point
        else
          render json: @route_point.errors, status: :unprocessable_entity
        end
      }
    end
  end

  # POST /route_points_batch.json
  def create_multiple
  	JSON.parse(request.raw_post)['route_points'].each do |point|
      point['gps_time'] = DateTime.parse(point['gps_time'])
      @route_point = RoutePoint.new(point)
      @route_point.save
    end
    @route_points = RoutePoint.all
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end

  # PATCH/PUT /route_points/1
  # PATCH/PUT /route_points/1.json
  def update
    respond_to do |format|
      if @route_point.update(route_point_params)
        format.html { redirect_to @route_point, notice: 'Route point was successfully updated.' }
        format.json { render :show, status: :ok, location: @route_point }
      else
        format.html { render :edit }
        format.json { render json: @route_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /route_points/1
  # DELETE /route_points/1.json
  def destroy
    @route_point.destroy
    respond_to do |format|
      format.html { redirect_to route_points_url, notice: 'Route point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route_point
      @route_point = RoutePoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_point_params
      params.require(:route_point).permit(:trip_id, :gps_time, :gps_longitude, :gps_latitude, :gps_speed, :cadence)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    respond_to do |format|
      format.html do
        @points = RoutePoint.where(:trip_id => @trip.id).order(:gps_time)
        @hash = Gmaps4rails.build_markers(@points) do |point, marker|
          marker.lat point.gps_latitude
          marker.lng point.gps_longitude
        end
      end
      format.json { }
    end
    #puts @hash
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/route_points_helper.rb
module RoutePointsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeBrainBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/route_points/_form.html.erb
<%= form_for(@route_point) do |f| %>
  <% if @route_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route_point.errors.count, "error") %> prohibited this route_point from being saved:</h2>

      <ul>
      <% @route_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.text_field :trip_id %>
  </div>
  <div class="field">
    <%= f.label :gps_time %><br>
    <%= f.datetime_select :gps_time %>
  </div>
  <div class="field">
    <%= f.label :gps_longitude %><br>
    <%= f.text_field :gps_longitude %>
  </div>
  <div class="field">
    <%= f.label :gps_latitude %><br>
    <%= f.text_field :gps_latitude %>
  </div>
  <div class="field">
    <%= f.label :gps_speed %><br>
    <%= f.text_field :gps_speed %>
  </div>
  <div class="field">
    <%= f.label :cadence %><br>
    <%= f.text_field :cadence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/route_points/edit.html.erb
<h1>Editing Route Point</h1>

<%= render 'form' %>

<%= link_to 'Show', @route_point %> |
<%= link_to 'Back', route_points_path %>

app/views/route_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Route Points</h1>

<table>
  <thead>
    <tr>
      <th>Trip</th>
      <th>Gps time</th>
      <th>Gps longitude</th>
      <th>Gps latitude</th>
      <th>Gps speed</th>
      <th>Cadence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @route_points.each do |route_point| %>
      <tr>
        <td><%= route_point.trip_id %></td>
        <td><%= route_point.gps_time %></td>
        <td><%= route_point.gps_longitude %></td>
        <td><%= route_point.gps_latitude %></td>
        <td><%= route_point.gps_speed %></td>
        <td><%= route_point.cadence %></td>
        <td><%= link_to 'Show', route_point %></td>
        <td><%= link_to 'Edit', edit_route_point_path(route_point) %></td>
        <td><%= link_to 'Destroy', route_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route point', new_route_point_path %>

app/views/route_points/new.html.erb
<h1>New Route Point</h1>

<%= render 'form' %>

<%= link_to 'Back', route_points_path %>

app/views/route_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip id:</strong>
  <%= @route_point.trip_id %>
</p>

<p>
  <strong>Gps time:</strong>
  <%= @route_point.gps_time %>
</p>

<p>
  <strong>Gps longitude:</strong>
  <%= @route_point.gps_longitude %>
</p>

<p>
  <strong>Gps latitude:</strong>
  <%= @route_point.gps_latitude %>
</p>

<p>
  <strong>Gps speed:</strong>
  <%= @route_point.gps_speed %>
</p>

<p>
  <strong>Cadence:</strong>
  <%= @route_point.cadence %>
</p>

<%= link_to 'Edit', edit_route_point_path(@route_point) %> |
<%= link_to 'Back', route_points_path %>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.title %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<p id="notice"><%= notice %></p>

<div align="center">
  <h1>
    <strong>Trip info: <%= @trip.title %></strong>
  </h1>
</div>

<table width="90%" align="center">
  <tr>
    <td width="80%" valign='top'>
      <div style='width: 100%; height: 800px;'>
        <div id="map" style='width: 100%; height: 100%;'></div>
      </div>
      <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({ internal: {id: 'map'}}, function(){
          var markers = handler.addMarkers(<%=raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      </script>
    </td>
    <td valign="top" width="20%">
      <table>
        <thead>
          <tr>
            <th>Gps time</th>
            <th>Gps longitude</th>
            <th>Gps latitude</th>
            <th>Gps speed</th>
            <th>Cadence</th>
          </tr>
        </thead>

        <tbody>
          <% @points.each do |point| %>
            <tr>
              <td><%= point.gps_time.strftime("%T") %></td>
              <td><%= point.gps_longitude %></td>
              <td><%= point.gps_latitude %></td>
              <td><%= point.gps_speed %></td>
              <td><%= point.cadence %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <td>
  </tr>
</table>

<%= link_to 'Back', trips_path %>

app/views/welcome/index.html.erb
<h2>BikeBrains</h2>
<p>
  <td><%= link_to 'Trips', controller: "trips", action: "index" %></td>
</p>